### ISSUE TITLE
Feature request: Bind to IPv4 and IPv6 in haproxy

### ISSUE THREAD

**Issue by saltydk** [Tecnativa/docker-socket-proxy#107]
Would be nice if we could make this support IPv6 by binding to IPv6 addresses in haproxy. It is fine if it is a toggle in case it breaks non-IPv6 usage.

**Comment by saltydk** [comment]
Made a fork to test it and https://github.com/saltydk/docker-socket-proxy/blob/b034b2ad9332cd9f39e736fff3d959951a6febb6/haproxy.cfg#L47 seems to work in both cases, IPv4 only and IPv6.

**Comment by pedrobaeza** [comment]
Please do the PR with the proposed change

**Comment by saltydk** [comment]
Done.
