### ISSUE TITLE
The latest version of Traefik (3.0) wants swarm's websocket can this support that on TCP 2377

### ISSUE THREAD

**Issue by Leopere** [Tecnativa/docker-socket-proxy#118]
The title is enough.

**Comment by Leopere** [comment]
Think this would be hard to add?  I don't really know what was referenced to get the current HAProxy config but it looks like swarm's API is a touch different then the default now and Traefik wants the swarm specific API.

**Comment by pedrobaeza** [comment]
You can propose any pull request adding this, and it will be reviewed.

**Comment by Leopere** [comment]
> You can propose any pull request adding this, and it will be reviewed.

Thanks I would hope so. I wasn’t wondering if i could write it if I could I probably just would’ve. It’s ok I’ll keep looking around.
