### ISSUE TITLE
versions newer than 0.1.1 fail to start with ipv6 disabled on host

### ISSUE THREAD

**Issue by Baine** [Tecnativa/docker-socket-proxy#124]
Greetings,

currently this app fails to launch with the below message if the host and docker have ipv6 disabled:
```
netdata_proxy  | [ALERT] 098/102718 (1) : Starting frontend dockerfrontend: cannot create listening socket [:::2375]
```

had to go back to 0.1.1 for it to start properly

would it be possible to allow for disabling ipv6 in the container, e.g. via ENV?

Thanks in advance,
and please let me know if you need additional information.

**Comment by sascha-schieferdecker** [comment]
I can confirm this behaviour

**Comment by Baine** [comment]
> Just use `DISABLE_IPV6` environment variable.

thank you, this works (should have checked the docker file)
tried "HAS_IPV6=false" previously, which failed

env block now looks like this, in case someone wants to copy it
```yaml
    environment:
      - CONTAINERS=1
      - DISABLE_IPV6=true
 ```

closing this now :)
