### ISSUE TITLE
Non-root user?

### ISSUE THREAD

**Issue by demyxco** [Tecnativa/docker-socket-proxy#22]
Hi, I tried building an image based on yours which would run as a non-priv user but breaks Traefik.

Traefik log
```
time="2019-11-30T11:40:00Z" level=error msg="Failed to retrieve information of the docker client and server host: Error response from daemon: <html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>" providerName=docker
time="2019-11-30T11:40:00Z" level=error msg="Provider connection error Error response from daemon: <html><body><h1>503 Service Unavailable</h1>\nNo server is available to handle this request.\n</body></html>, retrying in 462.318748ms" providerName=docker
```

Dockerfile
```
FROM tecnativa/docker-socket-proxy

# Create demyx user
RUN set -ex; \
    addgroup -g 1000 -S demyx; \
    adduser -u 1000 -D -S -G demyx demyx

# Finalize
RUN set -ex; \
    touch /tmp/server-state; \
    sed -i "s|pidfile /run|pidfile /tmp|g" /usr/local/etc/haproxy/haproxy.cfg; \
    sed -i "s|/var/lib/haproxy|/tmp|g" /usr/local/etc/haproxy/haproxy.cfg

USER demyx
```

Using `tecnativa/docker-socket-proxy` makes Traefik work but I don't wanna run this container as root with --privileged. Any help is appreciated!

**Comment by demyxco** [comment]
I think the issue is that the non-priv user in the container can't read the docker.sock. I don't see an entrypoint in your Dockerfile, how is haproxy initiated?

**Comment by SuperSandro2000** [comment]
It uses the entrypoint and cmd from the parent image. See https://github.com/docker-library/haproxy/blob/bbd9a3d20e2bda908eec696df9e6731bae448095/1.9/Dockerfile#L67

**Comment by demyxco** [comment]
@SuperSandro2000 yeah sorry I forgot to reply back, I eventually found it but yeah it doesn't work when I added sudo in the container.

**Comment by demyxco** [comment]
I'm gonna have to settle with this setup, which removes all shells from the container so nobody can chroot into it.

```
FROM tecnativa/docker-socket-proxy 

# Remove shells
RUN set -ex; \
	rm -f /bin/sh; \
	rm -f /bin/ash

ENTRYPOINT ["haproxy", "-W", "-db", "-f", "/usr/local/etc/haproxy/haproxy.cfg"]
```

Thanks for this wonderful project!

**Comment by SuperSandro2000** [comment]
Or you just use `FROM scratch` and copy only the necessary stuff into it.

**Comment by demyxco** [comment]
Yeah I tried that but HAProxy complained about missing libs.

**Comment by SuperSandro2000** [comment]
Then you need to copy those libs, too. How you are doing it is kinda backwards also it does not provide real security.

**Comment by demyxco** [comment]
Doesn't scratch run as root too?

**Comment by demyxco** [comment]
I'll try the scratch route when I have time, thanks again.

**Comment by SuperSandro2000** [comment]
> Doesn't scratch run as root too?

Not like there is anything in the container that would benefit from root.

**Comment by Yajo** [comment]
One idea:

1. Add a user in your host with docker permissions: `adduser --uid 999 -aG docker`
1. Run the container as that user `docker container run -u 999 tecnativa/docker-socket-proxy`

However, actually accessing the docker socket means the same (or higher) level of permissions as being root. Why care about this?
