### ISSUE TITLE
Built an image for ARM

### ISSUE THREAD

**Issue by derekhendrickx** [Tecnativa/docker-socket-proxy#23]
Hi!

I wanted to use this image on my Raspberry Pi so I cloned the repository and built an image for ARM. How could I share it so it's available on Docker Hub and/or this repository? I noticed there's already a discussion about supporting multi-architecture builds (cf. https://github.com/Tecnativa/docker-socket-proxy/issues/17) but I only see `amd64` on Docker Hub.

Thanks in advance!

![tecnativa_docker-socket-proxy Tags - Docker Hub - ](https://user-images.githubusercontent.com/1218149/70627783-d3f15480-1bf4-11ea-8d89-5bf9ab46e6b8.jpg)

**Comment by hansnn** [comment]
Is the image you built available somewhere? Would like to use it myself if possible.

**Comment by Yajo** [comment]
Sorry, I forgot to enable them after merging #18. It's done now, just check tags in docker hub now.
