### ISSUE TITLE
Update to HAProxy 2?

### ISSUE THREAD

**Issue by stumpylog** [Tecnativa/docker-socket-proxy#28]
HAProxy 1.9 looks to be about 1.5 years old.  Meanwhile HAProxy 2.2 is noted as being an LTS release, which might be a good base for this container.

I locally updated the image to use haproxy:2.2-alpine and the configuration file didn't produce any errors when tested using this version.  Any thoughts about updating to a more recent HAProxy?

**Comment by Yajo** [comment]
I'd love that, although TBH this project needs some more love than just updating to a newer HAProxy.

I would probably switch it to using Traefik 2 instead, which is what I'm using these days and is much easier to configure. What would the community think about that?

I also need to add tests.

And the biggest problem is that this works perfectly as it is, so it's hard to justify deep changes :sweat_smile:

**Comment by stumpylog** [comment]
Personally, I prefer the embedded HAProxy,  It's much easier to connect to another container inside a compose file, such as netdata, rather than needing Traefik 2, etc configured.

**Comment by robertbaker** [comment]
@Yajo Which is lighter weight? I use traefik v2, I have 2 instances already, one public, one internal-only. Is it possible to proxy the socket without using an embedded traefik/haproxy and instead rely on an external container?

For the time being, could you update to the latest HAProxy and build a new image?

**Comment by Yajo** [comment]
>  It's much easier to connect to another container inside a compose file, such as netdata, rather than needing Traefik 2, etc configured.

Yes, the idea'd be the same, just using a different proxy that I'm more used to.



> Which is lighter weight?

No idea, but it shouldn't be a big difference in any case.



> Is it possible to proxy the socket without using an embedded traefik/haproxy and instead rely on an external container?

To proxy the socket you need... a proxy! :tada: :smile: 

It can be in a container or not, that's up to you.



> please could you update to the latest HAProxy and build a new image?

I'll try, although I admit that it is low priority here. A PR would help. I labeled this as Hacktoberfest, maybe somebody wants a T-Shirt and accelerates this :blush:

**Comment by javieryanez** [comment]
> 
> 
> @Yajo Which is lighter weight? 

HAProxy seems a little lighter on the use of memory. In my system the current version of docker-socket-proxy is using 19MB of RAM meanwhile Traefik2, with a simple configuration, is using 42MB.
