### ISSUE TITLE
Large storage utulisation

### ISSUE THREAD

**Issue by FA9US** [Tecnativa/docker-socket-proxy#39]
running as a container i can see it took up to 25GB on space. what is it exactly caching/collecting? reboot didn't cleanup

**Comment by pedrobaeza** [comment]
It seems an error that is continuously getting logged

**Comment by joao-p-marques** [comment]
Yes, could you try removing the container and creating a new one?

**Comment by Yajo** [comment]
Assuming that's the problem, the solution is to configure a proper logging driver in your docker engine. The default one is JSON and it implements no log rotation, so it only grows.
