### ISSUE TITLE
logging is broken

### ISSUE THREAD

**Issue by seriousben** [Tecnativa/docker-socket-proxy#4]
``` 
haproxy-systemd-wrapper: executing /usr/local/sbin/haproxy -p /run/haproxy.pid -f /usr/local/etc/haproxy/haproxy.cfg -Ds
[WARNING] 222/173808 (6) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
[ALERT] 222/173808 (6) : sendmsg logger #1 failed: No such file or directory (errno=2)
[ALERT] 222/173808 (6) : sendmsg logger #1 failed: No such file or directory (errno=2)
```

**Comment by pedrobaeza** [comment]
My colleague @Yajo, who is on charge of this, is on holidays next week, but he will look to this when he returns.

**Comment by d-j-c** [comment]
This is an issue with the parent haproxy docker image. https://github.com/dockerfile/haproxy/issues/3

**Comment by d-j-c** [comment]
It looks like adding the volume mount of `-v /dev/log:/dev/log` will allow logs to be shown in the hosts logs:

```
$ docker container run \
    -d --privileged \
    --name dockerproxy \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /dev/log:/dev/log \
    -p 127.0.0.1:2375:2375 \
    tecnativa/docker-socket-proxy
```

```
sudo journalctl -f -l SYSLOG_IDENTIFIER=haproxy

Aug 18 16:03:32 localhost.local haproxy[29475]: Proxy dockerbackend started.
Aug 18 16:03:32 localhost.local haproxy[29475]: Proxy dockerfrontend started.
Aug 18 16:03:50 localhost.local haproxy[29479]: 172.17.0.1:37478 [18/Aug/2017:06:03:50.040] dockerfrontend dockerfrontend/<NOSRV> 0/-1/-1/-1/0 403 189 - - PR-- 0/0/0/0/0 0/0 "GET /v1.24/containers/json HTTP/1.1"
```

While this doesn't fit the standard of logging to stdout for consumption of `docker logs` it is _something_. I think to have logging to stdout it would likely require further work to add rsyslog and then something to pipe to stdout from there, or possibly a further customised systemd wrapper - both of which may be best dealt with by not using the haproxy base image.

**Comment by Yajo** [comment]
Actually I proposed a fix, but it has some problems and got stalled: https://github.com/docker-library/haproxy/pull/39

Possibly I should update that PR and make it entrypoint with https://github.com/Yelp/dumb-init

**Comment by joao-p-marques** [comment]
I think this is fixed now thanks to https://github.com/docker-library/haproxy/pull/39#issuecomment-448814374, right?
We still get
```
[WARNING] 302/115227 (1) : Can't open server state file '/var/lib/haproxy/server-state': No such file or directory
```
but logging to stdout seems to be working.

Closing this, but if the problem persists, fell free to reopen.
