### ISSUE TITLE
Stop containers with Portainer

### ISSUE THREAD

**Issue by raelyan** [Tecnativa/docker-socket-proxy#88]
Hi!

With the following configuration I can't stop containers with Portainer:

    environment:
      - LOG_LEVEL=info
      - ALLOW_RESTARTS=1
      # Access granted by default
      - EVENTS=1
      - PING=1
      - VERSION=1
      # Access revoked by default
        # Security-critical
      - AUTH=0
      - SECRETS=0
      - POST=0
        # Not always needed
      - BUILD=0
      - COMMIT=0
      - CONFIGS=0
      - CONTAINERS=1
      - DISTRIBUTION=0
      - EXEC=0
      - GRPC=0
      - IMAGES=1
      - INFO=1
      - NETWORKS=1
      - NODES=0
      - PLUGINS=0
      - SERVICES=1
      - SESSION=0
      - SWARM=0
      - SYSTEM=0
      - TASKS=1
      - VOLUMES=1

I don't know if it is a bug or I am not understanding it correctly. But I think ALLOW_RESTARTS=1 should allow me to do this.

Does anyone know what can happen? Is it necessary to activate POST? If I turn on POST and ALLOW_RESTARTS at the same time, does it only allow "stop, restart and kill" or turn on all POST options?.

Thank you very much.

**Comment by r-ushil** [comment]
Looks like it only turns POST on for endpoints you've allowed:

Below is an excerpt from `/usr/local/etc/haproxy/haproxy.cfg` from inside the container. This follows the "fall-through" style rules detailed here: https://cbonte.github.io/haproxy-dconv/1.7/configuration.html#4-http-request

![image](https://github.com/Tecnativa/docker-socket-proxy/assets/80212345/0d1ac785-bd78-4e30-9acd-ad4d76845dff)
